from enum import Enum


class ErrorCode(str, Enum):
    PASSWORD_MUST_BE_AT_LEAST_6_CHARACTERS = "PASSWORD_MUST_BE_AT_LEAST_6_CHARACTERS"
    FORBIDDEN = "FORBIDDEN"
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    USER_NOT_FOUND = "USER_NOT_FOUND"
    EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS"
    COMPANY_NOT_FOUND = "COMPANY_NOT_FOUND"
    BRANCH_NOT_FOUND = "BRANCH_NOT_FOUND"
    JOB_REQUIREMENT_NOT_FOUND = "JOB_REQUIREMENT_NOT_FOUND"
    ACTOR_NOT_FOUND = "ACTOR_NOT_FOUND"
    TOO_MANY_REQUESTS = "TOO_MANY_REQUESTS"
    INVALID_TOKEN = "INVALID_TOKEN"
    OTP_EXPIRED = "OTP_EXPIRED"
    INVALID_OTP = "INVALID_OTP"
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
    